# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pandas_service_pb2 as pandas__service__pb2


class PandasServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunMethod = channel.unary_unary(
                '/PandasService/RunMethod',
                request_serializer=pandas__service__pb2.MethodRequest.SerializeToString,
                response_deserializer=pandas__service__pb2.MethodResponse.FromString,
                )


class PandasServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunMethod(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PandasServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.RunMethod,
                    request_deserializer=pandas__service__pb2.MethodRequest.FromString,
                    response_serializer=pandas__service__pb2.MethodResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PandasService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PandasService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PandasService/RunMethod',
            pandas__service__pb2.MethodRequest.SerializeToString,
            pandas__service__pb2.MethodResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
