# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pandas_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14pandas_service.proto\"#\n\rMethodRequest\x12\x12\n\ninput_json\x18\x01 \x01(\t\"G\n\x0eMethodResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t2?\n\rPandasService\x12.\n\tRunMethod\x12\x0e.MethodRequest\x1a\x0f.MethodResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pandas_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _METHODREQUEST._serialized_start=24
  _METHODREQUEST._serialized_end=59
  _METHODRESPONSE._serialized_start=61
  _METHODRESPONSE._serialized_end=132
  _PANDASSERVICE._serialized_start=134
  _PANDASSERVICE._serialized_end=197
# @@protoc_insertion_point(module_scope)
